version: "3.8"

services:
  api:
    build: .
    container_name: muhyak-ai
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "127.0.0.1:3322:8000"

  rq-worker:
    build: .
    container_name: muhyak-rq-worker
    command: python worker.py
    env_file: .env
    depends_on:
      - api
      - redis

  rq-dashboard:
    build: .
    container_name: muhyak-rq-dashboard
    command: rq-dashboard --redis-url redis://redis:6379 --port 9181
    ports:
      - "9181:9181"


  redis:
    image: redis:7
    container_name: muhyak-redis
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10


  db:
    image: postgres:15
    container_name: photos-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  redis_data:
