version: "3.8"

services:
  api:
    build: .
    container_name: muhyak-ai
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "3322:8000"

  rq-worker:
    build: .
    container_name: muhyak-rq-worker
    command: python worker.py
    env_file: .env
    depends_on:
      - redis
      - api

  db:
    image: postgres:15
    container_name: photos-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: muhyak-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pg_data:
  redis_data:
