version: "3.8"

services:
  api:
    build: .
    container_name: photos-ml-api
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "3001:8000"
    # For live code reload in dev, uncomment the next 2 lines and run uvicorn instead of gunicorn
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: photos-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: photos-redis
    ports:
      - "6379:6379"

volumes:
  pg_data:
