version: "3.8"

services:
  api:
    build: .
    container_name: muhyak-ai
    env_file: .env
    depends_on:
      - db
    ports:
      - "127.0.0.1:3322:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rq-worker:
    build: .
    container_name: muhyak-rq-worker
    command: python worker.py
    env_file: .env
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rq-dashboard:
    build: .
    container_name: muhyak-rq-dashboard
    command: rq-dashboard --redis-url redis://host.docker.internal:6379 --port 9181
    ports:
      - "9181:9181"
    extra_hosts:
      - "host.docker.internal:host-gateway"


  db:
    image: postgres:15
    container_name: photos-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  redis_data:
